package basics.array

fun main() {
    val cars = arrayOf("Volvo", "BMW", "Ford", "Mazda")
    println(cars[0]) // Outputs Volvo
    cars.first()
    cars[0] = "Opel"
    println(cars[0])


    if ("Volvo" in cars) {
        println("It exists!")
    } else {
        println("It does not exist.")
    }

    val names = arrayOf("Seif", "Hazem", "Kareem", "Ahmed")
    for (name in names) {
        println(name)
    }
    println(names.toString())
    println(names.javaClass.toString() + names.hashCode())
    val s = "ffff"
    println(s.javaClass.toString() + s.hashCode())

    /**
        [Ljava.lang.String;: This part indicates the type of the object being printed.
        []: Denotes an array.
        L: Represents that the array elements are objects.
        java.lang.String: Specifies the type of the objects within the array (in this case, strings).
        @37bba400: This is the object's hash code, a unique identifier generated by the JVM (Java Virtual Machine) for the specific instance of the array names in memory. It's not directly related to the array's content.

        Note: Even within the same program run, the JVM might choose a different memory location for the array due to various factors like memory management strategies and optimizations.
     **/

    var riversArray = arrayOf("Nile", "Amazon", "Yangtze")
    // Using the += assignment operation creates a new riversArray,
    // copies over the original elements and adds "Mississippi"
    riversArray += "Mississippi"
    println(riversArray[3])
    // Nile, Amazon, Yangtze, Mississippi

//          val mixed:Array<Any> = arrayOf(1, "Seif", 2, "Mohamed",'k',4.23379)
//            for (i in 0 until  mixed.size){
//                val test = mixed[i].toString() + " Any"
//                println(test)
//            }



}
